### ISSUE TITLE
Feature: Add option to change the default sorting order

### ISSUE THREAD

**Issue by Marin-Kitagawa** [files-community/Files#11053]
### What feature or improvement do you think would benefit Files?

Right now, I can only see the default sorting option (for e.g. Date Modified). But there is not option to change the order (Ascending or Descending). Could you please incorporate this feature?

### Requirements

Include an option for default sorting order

### Files Version

```yml
Version: 2.4.21.0
OS Version: 10.0.22621.1105
```

### Windows Version
```yml
Edition:	Windows 11 Pro 
Version:	22H2 
OS build:	22621.1105 
Experience:	Windows Feature Experience Pack 1000.22638.1000.0
```
