### ISSUE TITLE
CI: Introduce GitHub Actions to bump up Files version

### ISSUE THREAD

**Issue by 0x5bfa** [files-community/Files#11590]
### What feature or improvement do you think would benefit Files?

1. Push a commit to bump up version (Update Package.appxmanifest)
2. Create a new tag
3. Add a new release
4. Add release note for it (Also adding this to Release-Notes repo)
5. Publish it

This five-step definitely makes Files team feel bad.

If we can be done this, `github-actions [bot]` will do all.

### Rationale

Before doing this, I'd like to merge `Files.App (Packages)` into `Files.App`, create 3 Package.appxmanifest for Dev, Preview, Stable, and remove xml editing tasks in the CI. Therefore bumping version will costly annoy team.

### Requirements

Capability | Priority
--- | ---
Add GitHub Actions | Must
Add a task to bump up | Must
Add a task to create a new tag | Should
Add a task to create a new release | Should
Add a task to publish it | Should

### Files Version

Version 2.0.40

### Windows Version

Windows 11 23H2

### Comments

Code:
```yml
name: Files Version Bump Workflow
run-name: Bump up Files version to ${{ inputs.new_version }} by @${{ github.actor }}
on:
    workflow_dispatch:
        inputs:
            new_version:
                required: true

jobs:
    resources:
        name: Update resources
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Update Package.appxmanifest
              run: |
                  sed -i "s/<Identity Name=\"\(.*\)\" Publisher=\"\(.*\)\" Version=\"\(.*\)\" \/>/<Identity Name=\"\1\" Publisher=\"\2\" Version=\"${{ inputs.files_new_version }}\" \/>/g" "src/Files.App (Package)/Package.appxmanifest"
            - name: Create a new PR for changes
              uses: peter-evans/create-pull-request@v4
              with:
                token: ${{ secrets.ACCESS_TOKEN }}
                commit-message: 'Package: Bump Files to ${{ inputs.new_version }}'
                committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
                signoff: false
                branch: ${{ github.actor }}/bump-up-to-${{ inputs.new_version }}
                delete-branch: true
                title: 'Package: Bump Files to ${{ inputs.new_version }}'
                body: |
                    *This PR was created by automation with GitHub Actions*<br>
                    Bumps Files to 45.2.0.
                labels: |
                    automation
                reviewers: ${{ github.actor }}
                draft: false
```
