### ISSUE TITLE
Feature: Automatically log issues on GitHub

### ISSUE THREAD

**Issue by Lamparter** [files-community/Files#16702]
### What feature or improvement do you think would benefit Files?

When you add an ID to a YAML marker in an issue template, e.g.:
```yaml
  # Files Version
  - type: input
    id: files_version # <-- THIS
    attributes:
      label: Files Version
```

You can then generate a URI to auto fill that value.
Try it out at [`https://github.com/files-community/Files/issues/new?template=bug_report.yml&files_version=abc123`](https://github.com/files-community/Files/issues/new?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen&template=bug_report.yml&files_version=abc123)!

The app should be able to launch a URI when an error occurs, or this generated link could appear in the log file.

### Requirements

- Add `id` attribute to each field of issue template
- Write a helper to calculate the URL for a stack trace
- `(automatically|prompt to)` open the URL when Files crashes

### Files Version

3.8.11.0

### Windows Version

10.0.22631.4602
